package com.ttasm.client.dao;

import com.ttasm.client.pojo.Ticket;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

@Mapper

public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int insert(Ticket row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    @Select("select * from ticket where `ticket_ID`=#{ticketId}")
    Ticket selectByPrimaryKey(String ticketId);


    List<Ticket> selectAll();


    @Select("select * from ticket where train_number = #{trainNumber}")
    List<Ticket> selectByTrainNumber(String trainNumber);

    @Select("select * from ticket where train_number = #{trainNumber} and state = \"for sale\"")
    List<Ticket> selectForSaleByTrainNumber(String trainNumber);

    int updateByPrimaryKey(Ticket row);
    @Update("update ticket set `state`=#{state} where `ticket_ID`=#{ticket_ID}")
    int updateState(String ticket_ID,String state);
}