package com.ttasm.client.dao;

import com.ttasm.client.pojo.Tricket;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper

public interface TricketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tricket
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tricket
     *
     * @mbg.generated
     */
    int insert(Tricket row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tricket
     *
     * @mbg.generated
     */
    Tricket selectByPrimaryKey(String ticketId);


    List<Tricket> selectAll();


    @Select("select * from tricket where train_number = #{trainNumber}")
    List<Tricket> selectByTrainNumber(String trainNumber);

    @Select("select * from tricket where train_number = #{trainNumber} and state = \"for sale\"")
    List<Tricket> selectForSaleByTrainNumber(String trainNumber);

    int updateByPrimaryKey(Tricket row);
}